### PR TITLE
Add 'img' to list of "link" elements in clickedItemIsLink function

### PR DESCRIPTION
**Pull request by mpelzsherman**
Fix for https://www.pivotaltracker.com/story/show/65483744

TODO: add test! (Wanted to get some feedback on this ASAP.)

### CODE REVIEW

**Comment by kaborso** [comment]
Can we not pass `img` along with other settings upon initialization for specific sites which include autotagging?

**Comment by mpelzsherman** [comment]
I think the list of items that should be considered "links" should be kept in sync with the items bound in  @clickBindSelector. In fact, maybe we can just do:

`if (jQTarget.is(@clickBindSelector))`

??

**Comment by kaborso** [comment]
I agree that `@clickBindSelector` should be used for `clickedElementIsLink`.

Regarding `img`... not all of our images are links, but many of them are, so perhaps it's okay to do include it by default (i.e. fire an event whenever someone else clicks on an `img` element)?

**Comment by mpelzsherman** [comment]
`clickedElementIsLink` does not determine whether to fire an event. The event is going to fire regardless. `clickedElementIsLink` determines whether to use the element itself or its parent to find the `item` ID. Any img element that gets into this code is, by definition, a "link". So yes - I think it's OK to include 'img' by default. Also, `@clickBindSelector` can be overridden if needed.

**Comment by kaborso** [comment]
(I was referring to `clickBindSelector` when I mentioned the default.)

**Comment by kaborso** [comment]
I get this error when I run the Jasmine suite

```
TypeError: Cannot read property 'cg' of null
    at WH.fire (http://localhost:8888/jquery.autotagging.js:179:26)
    at WH.fire (http://localhost:8888/jquery.autotagging.js:3:63)
    at null.<anonymous> (http://localhost:8888/__spec__/AutotaggingSpec.js:47:12)
    at jasmine.Block.execute (http://localhost:8888/__jasmine__/jasmine.js:1064:17)
    at jasmine.Queue.next_ (http://localhost:8888/__jasmine__/jasmine.js:2096:31)
    at onComplete (http://localhost:8888/__jasmine__/jasmine.js:2092:18)
    at jasmine.WaitsForBlock.execute (http://localhost:8888/__jasmine__/jasmine.js:2576:5)
    at http://localhost:8888/__jasmine__/jasmine.js:2590:12
```

**Comment by zph** [comment]
@kaborso The tests were fixed after this branched off I believe. I'll try rebasing it.

It's a long & boring story for why they didn't work... but seeing if I can fix w/o having to merge in the other outstanding PR.

**Comment by zph** [comment]
@kaborso Pull & give it another go please :)

After the rebase it ran w/ 32/32 passing.

**Comment by kaborso** [comment]
Pulled and ran. Hooray for green!

**Comment by kaborso** [comment]
:+1:

**Pull request merged**
