### PR TITLE
[ET][83212064] used gulp more heavily, moved distributed files into dist...

### PR DESCRIPTION
**Pull request by Ebtoulson**
... directory, added an non-amd tool to build a non-amd version of autotagging

redo of https://github.com/primedia/jquery-autotagging/pull/22
I decided not to change the `jquery.autotagging` module to be a singleton since I was running into problems with the tests. 

Created a gulp task to un-AMD jquery-autotagging (except for jquery and jquery cookie).
- [x] js tests pass

### CODE REVIEW

**Comment by mpelzsherman** [comment]
Please update the README to reflect any changes with setup, development, and testing workflow.

After running "bower install" and "npm install", I am still getting the following error from "gulp":

Error: Cannot find module 'gulp-util'

**Comment by Ebtoulson** [comment]
@mpelzsherman  yea thanks for reminding me. I really want to improve the docs for this project since its really difficult to understand just how to get it working if youre not familiar it (ie the lastLinkClicked issue).

Looks like I removed the dev dependency but left the `require` and since I didn't clear out my `node_modules` I didn't see any issues. Pull the last commit and it should be fixed.

**Comment by mpelzsherman** [comment]
Confirmed the gulp fix. Are you going to add a gulp task for running the jasmine tests?

**Comment by Ebtoulson** [comment]
I was thinking about, if only to stick with one tool, but I haven't tried it yet.

**Comment by c0** [comment]
I don't see a need to run jasmine with gulp at this point in this PR. That time could be spent setting up karma like [my-places.js](https://github.com/primedia/my-places.js)

**Comment by Ebtoulson** [comment]
I've updated the docs to include the `gulp` stuff and the non-amd version.

**Pull request merged**
