### PR TITLE
Polyfill for IE8

### PR DESCRIPTION
**Pull request by tb0yd**
@pasha @kaborso Hey, we're trying to fix this bug in Portal

https://www.pivotaltracker.com/story/show/64485196

Browserdetect already exists as a separate library and has been pushed to our jam server. Included in this pull request are changes to use that separate browserdetect library. 

Thanks!

### CODE REVIEW

**Comment by colinrymer** [comment]
We need to move the browserdetect spec over to that repo and update these specs before merging.

**Comment by colinrymer** [comment]
All specs now pass.

**Comment by kaborso** [comment]
:+1:

**Comment by kaborso** [comment]
Oops beat me to the comment. Looks like we're good to go!

**Pull request merged**
